export const CREATE_CHARACTER_REQUEST = "CREATE_CHARACTER_REQUEST";
export const CREATE_CHARACTER_SUCCESS = "CREATE_CHARACTER_SUCCESS";
export const CREATE_CHARACTER_FAILURE = "CREATE_CHARACTER_FAILURE";

export const READ_CHARACTERS_REQUEST = "READ_CHARACTERS_REQUEST";
export const READ_CHARACTERS_SUCCESS = "READ_CHARACTERS_SUCCESS";
export const READ_CHARACTERS_FAILURE = "READ_CHARACTERS_FAILURE";

export const UPDATE_CHARACTER_REQUEST = "UPDATE_CHARACTER_REQUEST";
export const UPDATE_CHARACTER_SUCCESS = "UPDATE_CHARACTER_SUCCESS";
export const UPDATE_CHARACTER_FAILURE = "UPDATE_CHARACTER_FAILURE";

export const DELETE_CHARACTER_REQUEST = "DELETE_CHARACTER_REQUEST";
export const DELETE_CHARACTER_SUCCESS = "DELETE_CHARACTER_SUCCESS";
export const DELETE_CHARACTER_FAILURE = "DELETE_CHARACTER_FAILURE";
