export const CREATE_CHARACTER_REQUEST = "CREATE_CHARACTER_REQUEST";
export const CREATE_CHARACTER_SUCCESS = "CREATE_CHARACTER_SUCCESS";
export const CREATE_CHARACTER_FAILURE = "CREATE_CHARACTER_FAILURE";

export const READ_CHARACTERS_REQUEST = "READ_CHARACTERS_REQUEST";
export const READ_CHARACTERS_SUCCESS = "READ_CHARACTERS_SUCCESS";
export const READ_CHARACTERS_FAILURE = "READ_CHARACTERS_FAILURE";

export const UPDATE_CHARACTER_REQUEST = "UPDATE_CHARACTER_REQUEST";
export const UPDATE_CHARACTER_SUCCESS = "UPDATE_CHARACTER_SUCCESS";
export const UPDATE_CHARACTER_FAILURE = "UPDATE_CHARACTER_FAILURE";

export const DELETE_CHARACTER_REQUEST = "DELETE_CHARACTER_REQUEST";
export const DELETE_CHARACTER_SUCCESS = "DELETE_CHARACTER_SUCCESS";
export const DELETE_CHARACTER_FAILURE = "DELETE_CHARACTER_FAILURE";

export const CREATE_CAMPAIGN_REQUEST = "CREATE_CAMPAIGN_REQUEST";
export const CREATE_CAMPAIGN_SUCCESS = "CREATE_CAMPAIGN_SUCCESS";
export const CREATE_CAMPAIGN_FAILURE = "CREATE_CAMPAIGN_FAILURE";

export const READ_CAMPAIGNS_REQUEST = "READ_CAMPAIGNS_REQUEST";
export const READ_CAMPAIGNS_SUCCESS = "READ_CAMPAIGNS_SUCCESS";
export const READ_CAMPAIGNS_FAILURE = "READ_CAMPAIGNS_FAILURE";

export const UPDATE_CAMPAIGN_REQUEST = "UPDATE_CAMPAIGN_REQUEST";
export const UPDATE_CAMPAIGN_SUCCESS = "UPDATE_CAMPAIGN_SUCCESS";
export const UPDATE_CAMPAIGN_FAILURE = "UPDATE_CAMPAIGN_FAILURE";

export const DELETE_CAMPAIGN_REQUEST = "DELETE_CAMPAIGN_REQUEST";
export const DELETE_CAMPAIGN_SUCCESS = "DELETE_CAMPAIGN_SUCCESS";
export const DELETE_CAMPAIGN_FAILURE = "DELETE_CAMPAIGN_FAILURE";

export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";

export const LOG_OUT_REQUEST = "LOG_OUT_REQUEST";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE";

export const READ_USER_REQUEST = "READ_USER_REQUEST";
export const READ_USER_SUCCESS = "READ_USER_SUCCESS";
export const READ_USER_FAILURE = "READ_USER_FAILURE";
