export const CREATE_CHARACTERS_REQUEST = "CREATE_CHARACTERS_REQUEST";
export const CREATE_CHARACTERS_SUCCESS = "CREATE_CHARACTERS_SUCCESS";
export const CREATE_CHARACTERS_FAILURE = "CREATE_CHARACTERS_FAILURE";

export const READ_CHARACTERS_REQUEST = "READ_CHARACTERS_REQUEST";
export const READ_CHARACTERS_SUCCESS = "READ_CHARACTERS_SUCCESS";
export const READ_CHARACTERS_FAILURE = "READ_CHARACTERS_FAILURE";

export const UPDATE_CHARACTERS_REQUEST = "UPDATE_CHARACTERS_REQUEST";
export const UPDATE_CHARACTERS_SUCCESS = "UPDATE_CHARACTERS_SUCCESS";
export const UPDATE_CHARACTERS_FAILURE = "UPDATE_CHARACTERS_FAILURE";

export const DELETE_CHARACTERS_REQUEST = "DELETE_CHARACTERS_REQUEST";
export const DELETE_CHARACTERS_SUCCESS = "DELETE_CHARACTERS_SUCCESS";
export const DELETE_CHARACTERS_FAILURE = "DELETE_CHARACTERS_FAILURE";
